---
# install php related packages
  - name: install php packages
    package:
      name: "{{ item }}"
      state: installed
    with_items:
      - php
      - php-mysql
    notify: Restart apache service
